apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-claims
  namespace: incapsula-demo
spec:
  project: default
  source:
    repoURL: 'https://github.com/kernel-kun/incapsula_demo'
    targetRevision: HEAD
    path: incapsulaClaims
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: incapsula-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
